### ISSUE TITLE
I got a failure on the vim-airline-theme

### ISSUE THREAD

**Issue by blairanderson** [searls/icloud-dotfiles#3]
Thanks for publishing this repo and keeping stuff updated. 

I'm not looking for a fix, just an FYI:

```bash
Cloning into '/Users/blairanderson/~/Library/Mobile Documents/com~apple~CloudDocs/dotfiles/.vim/bundle/vim-airline-themes'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:vim-airline/vim-airline-themes.git' into submodule path '/Users/blairanderson/~/Library/Mobile Documents/com~apple~CloudDocs/dotfiles/.vim/bundle/vim-airline-themes' failed
Failed to clone '.vim/bundle/vim-airline-themes' a second time, aborting
```

**Comment by searls** [comment]
I am not able to replicate this when running `git clone --recursive` on this repo. The `.gitmodules` file also appears correct. And the repo definitely seems to be there: https://github.com/vim-airline/vim-airline-themes

Maybe your SSH private key isn't set up / in github and it's not letting you clone?

**Comment by blairanderson** [comment]
Ohhh goodness you are 🎯 

Thank you!
